### ISSUE TITLE
segfaults when removing files

### ISSUE THREAD

**Issue by ousia** [ib/xarchiver#143]
@ib,

latest released version (`xarchiver-0.5.4.17-2.fc35.x86_64`, as packaged for _Fedora 35_) segfaults if I remove the file `mimetype` from [book-epub.zip](https://github.com/ib/xarchiver/files/8546204/book-epub.zip)

It happens all the time (I’d say with all most basic operations).

GBD gives the following error message:

```
Thread 1 "xarchiver" received signal SIGSEGV, Segmentation fault.
__strlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:74
74		VPCMPEQ	(%rdi), %ymm0, %ymm1
```

And here is the backtrace:

```
#0  __strlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:74
#1  0x00007ffff752f848 in g_string_insert_len
    (string=string@entry=0x5555557e74c0, pos=pos@entry=0, val=0x2 <error: Cannot access memory at address 0x2>, len=len@entry=-1) at ../glib/gstring.c:439
#2  0x00007ffff752fb35 in g_string_prepend (string=string@entry=0x5555557e74c0, val=<optimized out>) at ../glib/gstring.c:630
#3  0x000055555556e9d3 in xa_build_full_path_name_from_entry (entry=0x555555caf720) at /usr/src/debug/xarchiver-0.5.4.17-2.fc35.x86_64/src/archive.c:782
#4  0x00005555555926af in xa_update_window_with_archive_entries (archive=0x555555c13630, entry=0x555555caf720)
    at /usr/src/debug/xarchiver-0.5.4.17-2.fc35.x86_64/src/window.c:2936
#5  0x0000555555568daf in xa_dir_sidebar_row_selected (selection=<optimized out>, user_data=<optimized out>)
    at /usr/src/debug/xarchiver-0.5.4.17-2.fc35.x86_64/src/archive.c:866
#6  0x00007ffff7625aba in _g_closure_invoke_va
    (param_types=0x0, n_params=<optimized out>, args=0x7fffffffcf70, instance=0x555555b18300, return_value=0x0, closure=0x555555bec7d0) at ../gobject/gclosure.c:893
#7  g_signal_emit_valist (instance=0x555555b18300, signal_id=<optimized out>, detail=0, var_args=var_args@entry=0x7fffffffcf70) at ../gobject/gsignal.c:3406
#8  0x00007ffff7625c03 in g_signal_emit (instance=<optimized out>, signal_id=<optimized out>, detail=<optimized out>) at ../gobject/gsignal.c:3553
#9  0x00007ffff7ae1555 in gtk_tree_view_real_set_cursor (tree_view=0x555555a7b390, path=0x5555557854b0, flags=(CLEAR_AND_SELECT | CURSOR_INVALID))
    at ../gtk/gtktreeview.c:13326
#10 0x00007ffff7adb0ac in gtk_tree_view_row_deleted (model=<optimized out>, path=<optimized out>, data=0x555555a7b390) at ../gtk/gtktreeview.c:9408
#14 0x00007ffff7625c03 in <emit signal ??? on instance ???> (instance=<optimized out>, signal_id=<optimized out>, detail=<optimized out>) at ../gobject/gsignal.c:3553
    #11 0x00007ffff7607c7f in g_closure_invoke
    (closure=0x555555bec3d0, return_value=0x0, n_param_values=2, param_values=0x7fffffffd2f0, invocation_hint=0x7fffffffd270) at ../gobject/gclosure.c:830
    #12 0x00007ffff7624126 in signal_emit_unlocked_R
    (node=node@entry=0x5555557133e0, detail=detail@entry=0, instance=instance@entry=0x555555be59e0, emission_return=emission_return@entry=0x0, instance_and_params=instance_and_params@entry=0x7fffffffd2f0) at ../gobject/gsignal.c:3742
    #13 0x00007ffff76259ea in g_signal_emit_valist
    (instance=<optimized out>, signal_id=<optimized out>, detail=<optimized out>, var_args=var_args@entry=0x7fffffffd4c0) at ../gobject/gsignal.c:3497
#15 0x00007ffff7aca36c in gtk_tree_store_remove (tree_store=tree_store@entry=0x555555be59e0, iter=iter@entry=0x7fffffffd620) at ../gtk/gtktreestore.c:1231
#16 0x00007ffff7aca544 in gtk_tree_store_clear_traverse (node=0x555555ca92c0, store=store@entry=0x555555be59e0) at ../gtk/gtktreestore.c:1848
#17 0x00007ffff7aca518 in gtk_tree_store_clear_traverse (node=0x555555be6e70, store=store@entry=0x555555be59e0) at ../gtk/gtktreestore.c:1839
#18 0x00007ffff7aca5ee in gtk_tree_store_clear (tree_store=0x555555be59e0) at ../gtk/gtktreestore.c:1884
#19 0x000055555556eaf3 in xa_fill_dir_sidebar (archive=0x555555c13630, force_reload=<optimized out>)
    at /usr/src/debug/xarchiver-0.5.4.17-2.fc35.x86_64/src/archive.c:827
#20 0x00005555555928db in xa_update_window_with_archive_entries (archive=0x555555c13630, entry=0x0)
    at /usr/src/debug/xarchiver-0.5.4.17-2.fc35.x86_64/src/window.c:3007
#21 0x000055555558b9cb in xa_child_processed (process=<optimized out>, exitstatus=<optimized out>, archive=0x555555c13630)
    at /usr/src/debug/xarchiver-0.5.4.17-2.fc35.x86_64/src/window.c:816
#22 0x00005555555686e3 in xa_process_stdout (ioc=0x555555cb46c0, cond=G_IO_HUP, archive=0x555555c13630)
    at /usr/src/debug/xarchiver-0.5.4.17-2.fc35.x86_64/src/archive.c:80
#23 0x00007ffff750e0af in g_main_dispatch (context=0x55555561e370) at ../glib/gmain.c:3381
#24 g_main_context_dispatch (context=0x55555561e370) at ../glib/gmain.c:4099
--Type <RET> for more, q to quit, c to continue without paging--
#25 0x00007ffff7563308 in g_main_context_iterate.constprop.0 (context=0x55555561e370, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>)
    at ../glib/gmain.c:4175
#26 0x00007ffff750d7c3 in g_main_loop_run (loop=0x555555ca0fd0) at ../glib/gmain.c:4373
#27 0x00007ffff799043d in gtk_main () at ../gtk/gtkmain.c:1329
#28 0x00005555555675aa in main (argc=<optimized out>, argv=<optimized out>) at /usr/src/debug/xarchiver-0.5.4.17-2.fc35.x86_64/src/main.c:1390
```

Many thanks for your help.

**Comment by ib** [comment]
Can you compile current master and check whether it still segfaults?

**Comment by ousia** [comment]
Yes, it segfaults.

Don’t you experience a segfault too?

Many thanks for your help.

**Comment by ib** [comment]
> Don’t you experience a segfault too?

No, not on my PC. I'll test later with a notebook and with Fedora Live.

**Comment by ib** [comment]
I can confirm now, but I need to investigate under what circumstances it happens and why it doesn't happen all the time.

**Comment by ousia** [comment]
I have also an issue with Fedora 35 LXDE and Python.

It isn’t probably not related, but it might have a common root.

``` python
import cairo
```

I get the following error message:

```
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
```

And also an empty window with title text _Basic shapes_.

Needless to say, I installed all Python, GObject and Cairo dependencies.

**Comment by ib** [comment]
I could also reproduce the issue with Devuan, even though there was no segmentation fault. This only occurred with Fedora Live.

**Comment by ousia** [comment]
I wonder whether this may be related to X or Wayland.

But I must admit that the whole issue is all Greek to me.

**Comment by ousia** [comment]
@ib, many thanks for the patch.

I think it works (I mean, I have tested only with a single file).

**Comment by ousia** [comment]
Let me test this patch for some time.

After that, I think it would be great to have a new release.

Many thanks for your help.

**Comment by ib** [comment]
Did the patch fix the problem?

**Comment by ousia** [comment]
I haven’t tested it as much as I thought I could, but I think your patch has fixed the issue.
